# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

name:               "MeowPiE's Lab"
url:                "https://blog.meowpie.kr"
timezone:           Asia/Seoul
permalink:          /:title/
paginate:           5

author:
  name:             MeowPiE
  facebook:         # your-id
  youtubeUser:      # your-id
  youtubeChannel:   # your-id
  twitter:          magpiemeow
  github:           MeowPiE
  gitlab:           MeowPiE
  stackoverflow:    # your-id
  quora:            # your-id
  linkedin:         # your-id
  pinterest:        # your-id
  googlePlus:       # your-id
  instagram:        # your-id
  reddit:           # your-id
  medium:           # your-id
  tumblr:           # your-id
  email:            email@meowpie.kr
  google-analytics: UA-120899034-1
  disqus:           meowpies-lab

nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"

sass:
  sass_dir:         _sass
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
