# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

name:               "MeowPiE's Lab"
description:        "여러가지 이야기를 나누는 냥파이의 블로그<br>취미로 일상 이야기와 기록하고 싶은 내용을 담아두는 블로그입니다.
"
url:                "https://blog.meowpie.kr"
timezone:           Asia/Seoul
permalink:          /:title/
paginate:           5

author:
  name:             MeowPiE
  twitter:          magpiemeow
  github:           MeowPiE
  gitlab:           MeowPiE
  email:            email@meowpie.kr
  google-analytics: UA-120899034-1
  disqus:           meowpies-lab

nav:
  - name:           "about"
    url:            "/about"
  - name:           "archive"
    url:            "/archive"

sass:
  sass_dir:         _sass
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
