title:              "MeowPiE's Lab"
description:        여러가지 이야기를 나누는 냥파이의 블로그
about:              "깃허브 페이지로 호스팅 되는 냥파이의 개인 블로그 입니다.<br>냥파이에게 블로깅은 언제까지나 취미생활이며, 영리 목적으로 사용되지 않습니다."

url:                "https://blog.meowpie.kr"
timezone:           Asia/Seoul
permalink:          /:title/
paginate:           5

author:
  name:             MeowPiE
  twitter:          magpiemeow
  github:           MeowPiE
  gitlab:           MeowPiE
  email:            email@meowpie.kr
  google-analytics: UA-120899034-1
  disqus:           meowpies-lab

nav:
  - title:           "about"
    url:            "/about"
  - title:           "archive"
    url:            "/archive"

sass:
  sass_dir:         _sass
  style:            compressed

defaults:
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
